root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  include_ext = ["go", "tpl", "tmpl", "html", "sql"]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  exclude_re = ["_test.go"]

[misc]
  clean_on_exit = true
